<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.2</Version>
    <Deterministic>true</Deterministic>
    <Authors>沙漠尽头的狼</Authors>
    <Copyright>https://codewf.com</Copyright>
    <RepositoryUrl>https://github.com/dotnet9/Zitie</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/dotnet9/Zitie</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo.png</PackageIcon>
    <GenerateDocumentationFile Condition="'$(MSBuildProjectName)' != 'Zitie.Desktop'">true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)logo.png"
          Pack="true"
          PackagePath="\"
          Visible="false" />
  </ItemGroup>
</Project>
